algoritmo "Imparpar"
// Função : Verificar se o número digitado é impar ou par
// Autor : Marcus Vinícius Moreira
// Data : 28/06/2022

var
numero:real

inicio

//entrada

escreval("Vamos verificar se o número que você digitou é impar ou par.")
escreval("Digite um número")
leia(numero)

//processamento

se (numero mod 2=0) entao

   escreval("O número digitado é par")


senao

     escreval("O número digitado é ímpar")
     
     
fimse


fimalgoritmo