Algoritmo "incrementp_descremento"
// Descrição   : Criar incremento e descremento
// Autor(a)    : Marcus Vinícius Bizerra Moreira
// Data atual  : 23/08/2022
Var
cont, acu:inteiro


Inicio
escreval("----------------- LACO PARA - INCREMENTO  ------------")

para cont de 1 ate 20 passo 2 faca


escreval(cont)

fimpara

escreval("----------------- LACO PARA - DECREMENTO  ------------")

para cont de 20 ate 0 passo -1 faca


escreval(cont)

fimpara

Fimalgoritmo