Algoritmo "exercicio_10"
// Autor(a)    : Marcus Vinícius Bizerra Moreira
// Data atual  : 20/09/2022

Var
n1,n2,n3, cont: inteiro



Inicio

repita

   escreval("Digite um numero para calcular o fatorial dele")
   leia(n1)
   
   para cont de n1 ate 1 passo -1 faca

   n2<-n1*cont

   escreval("O fatorial do numero é:",n2)

   escreval("Para sair do lçao digite 1")
   leia(n3)

   limpatela

ate (n3=1)




      

Fimalgoritmo