Algoritmo "exercicio_8"
// Autor(a)    : Marcus Vinícius Bizerra Moreira
// Data atual  : 20/09/2022

Var
cont, acu, numero: inteiro
media: real


Inicio

repita
para cont de 1 ate 5 faca

 escreval("digite um numero para fazer a media")
 leia(numero)
             acu <- cont + acu
             media <- acu/5

          escreval(acu)
fimpara

ate (numero = 0)


Fimalgoritmo