Algoritmo "exercico_1"
// Autor(a)    : Marcus Vinícius Bizerra Moreira
// Data atual  : 06/09/2022

Var

n1,n2, cont:inteiro


Inicio

escreval("Exercício 1")
escreval("Preciso que você escreva 2 numeros, um inicial e um final")
escreval("Digite o numero inicial")
leia(n1)
escreval("Digite o numero final")
leia(n2)
limpatela

escreval("Exercício 1")


para cont de n1 ate n2 faca


     escreval(cont)

fimpara



Fimalgoritmo