Algoritmo "exercicio_3"
// Autor(a)    : Marcus Vinícius Bizerra Moreira
// Data atual  : 06/09/2022
Var

cont, n1:inteiro


Inicio

escreval("Exercício 3")
escreval("Vamos mostrar par você somento os numeros ímpares de 100 a 200")
escreval("Digite 1 para começar")
leia(n1)

limpatela

escreval("Exercício3")

para cont de 100 ate 200 faca
     se (cont%2=1) entao
        escreval(cont)
     fimse

fimpara


Fimalgoritmo