Algoritmo "exercicio_1"
// Autor(a)    : Marcus Vinícius Bizerra Moreira
// Data atual  : 01/11/2022

Var

vet: vetor[0..9]de inteiro
cont,soma:inteiro

Inicio

para cont de 0 ate 9 faca
     escreval("Digite um numero")
     leia (vet[cont])
     soma <- soma + (vet[cont])
     escreval("_________________________________________")
fimpara

escreval("A soma dos numeros digitado é: ", soma)
     
Fimalgoritmo