Algoritmo "Mediade3numeros"

// Descrição   : Solicita 3 numeros para calcular a sua media
// Autor(a)    : Marcus Moreira
// Data atual  : 08/03/2022

Var

n1, n2, n3, result:real

Inicio

//entrada

escreval("--------------------------------")
escreval("Digite o primeiro número")
escreval("--------------------------------")
leia(n1)
escreval("--------------------------------")
escreval("Digite o segundo número")
escreval("--------------------------------")
leia(n2)
escreval("--------------------------------")
escreval("Digite o terceiro número")
leia(n3)
escreval("--------------------------------")

//processamento

result <- (n1+n2+n3)/3
limpatela

//saida

escreval("--------------------------------")
escreval("A média é: ", result)
escreval("--------------------------------")


Fimalgoritmo